"""
Sample data for testing the compliance dashboard
"""

SAMPLE_JURISDICTIONS = [
    {"name": "United States", "code": "US", "region": "North America"},
    {"name": "European Union", "code": "EU", "region": "Europe"},
    {"name": "United Kingdom", "code": "UK", "region": "Europe"},
    {"name": "Singapore", "code": "SG", "region": "Asia"},
    {"name": "Hong Kong", "code": "HK", "region": "Asia"},
]

SAMPLE_COMPLIANCE_AREAS = [
    {
        "name": "Know Your Customer (KYC)",
        "description": "Customer identification and verification procedures",
        "jurisdiction_id": 1,
        "responsible_team": "Compliance Team",
    },
    {
        "name": "Anti-Money Laundering (AML)",
        "description": "Transaction monitoring and suspicious activity reporting",
        "jurisdiction_id": 1,
        "responsible_team": "Risk Team",
    },
    {
        "name": "Data Protection & Privacy",
        "description": "GDPR and data privacy compliance",
        "jurisdiction_id": 2,
        "responsible_team": "Legal Team",
    },
    {
        "name": "Asset Custody",
        "description": "Custody and safeguarding of customer assets",
        "jurisdiction_id": 1,
        "responsible_team": "Ops Team",
    },
    {
        "name": "Market Abuse Regulation (MAR)",
        "description": "Insider trading and market manipulation prevention",
        "jurisdiction_id": 2,
        "responsible_team": "Trading Compliance",
    },
]

SAMPLE_POSITION_LIMITS = [
    {
        "asset_symbol": "BTC",
        "max_position_usd": 500000000,
        "limit_percentage": 25.0,
        "warning_threshold": 80.0,
    },
    {
        "asset_symbol": "ETH",
        "max_position_usd": 300000000,
        "limit_percentage": 15.0,
        "warning_threshold": 75.0,
    },
    {
        "asset_symbol": "USDC",
        "max_position_usd": 200000000,
        "limit_percentage": 10.0,
        "warning_threshold": 85.0,
    },
    {
        "asset_symbol": "XRP",
        "max_position_usd": 50000000,
        "limit_percentage": 2.5,
        "warning_threshold": 75.0,
    },
    {
        "asset_symbol": "SOL",
        "max_position_usd": 75000000,
        "limit_percentage": 3.75,
        "warning_threshold": 80.0,
    },
]

SAMPLE_RISK_ASSESSMENTS = [
    {
        "compliance_area_id": 1,
        "risk_level": "medium",
        "risk_description": "Need to improve KYC verification speed",
        "mitigation_strategy": "Implement automated verification tools",
        "assessed_by": "John Smith",
    },
    {
        "compliance_area_id": 2,
        "risk_level": "high",
        "risk_description": "Transaction monitoring alert threshold may be too high",
        "mitigation_strategy": "Calibrate thresholds and add ML-based detection",
        "assessed_by": "Jane Doe",
    },
    {
        "compliance_area_id": 3,
        "risk_level": "low",
        "risk_description": "GDPR controls in place and functioning well",
        "mitigation_strategy": "Continue quarterly audits",
        "assessed_by": "Mike Johnson",
    },
]

# ── MTL License Sample Data ───────────────────────────────────────────────────
from datetime import datetime, timedelta

_now = datetime.utcnow()

SAMPLE_MTL_LICENSES = [
    {
        "state": "California",
        "state_code": "CA",
        "license_number": "DFPI-MTL-2021-0042",
        "regulator": "CA DFPI",
        "status": "active",
        "issue_date": _now - timedelta(days=900),
        "expiry_date": _now + timedelta(days=465),
        "renewal_due_date": _now + timedelta(days=375),
        "notes": "Annual renewal required. Last exam: Q1 2024, no findings.",
    },
    {
        "state": "New York",
        "state_code": "NY",
        "license_number": "NYDFS-VCE-0188",
        "regulator": "NYDFS",
        "status": "active",
        "issue_date": _now - timedelta(days=730),
        "expiry_date": _now + timedelta(days=60),
        "renewal_due_date": _now + timedelta(days=30),
        "notes": "BitLicense. Renewal application submitted 2025-01-15. URGENT: expires soon.",
    },
    {
        "state": "Texas",
        "state_code": "TX",
        "license_number": "TX-MSB-2022-1107",
        "regulator": "TX DOB",
        "status": "active",
        "issue_date": _now - timedelta(days=600),
        "expiry_date": _now + timedelta(days=200),
        "renewal_due_date": _now + timedelta(days=110),
        "notes": "Biennial renewal. No outstanding issues.",
    },
    {
        "state": "Florida",
        "state_code": "FL",
        "license_number": None,
        "regulator": "FL OFR",
        "status": "pending",
        "application_date": _now - timedelta(days=90),
        "notes": "Application submitted 2024-12-10. Awaiting OFR review. Expected Q2 2025.",
    },
    {
        "state": "Washington",
        "state_code": "WA",
        "license_number": "WA-MTL-2020-0055",
        "regulator": "WA DFI",
        "status": "active",
        "issue_date": _now - timedelta(days=1200),
        "expiry_date": _now + timedelta(days=340),
        "renewal_due_date": _now + timedelta(days=250),
        "notes": "No outstanding issues.",
    },
    {
        "state": "Illinois",
        "state_code": "IL",
        "license_number": "IL-TL-2019-0031",
        "regulator": "IL IDFPR",
        "status": "expired",
        "issue_date": _now - timedelta(days=1800),
        "expiry_date": _now - timedelta(days=30),
        "notes": "Renewal missed. Renewal application in process. Cease ops in IL until renewed.",
    },
    {
        "state": "Nevada",
        "state_code": "NV",
        "license_number": None,
        "regulator": "NV FID",
        "status": "pending",
        "application_date": _now - timedelta(days=45),
        "notes": "Initial application. Expecting 6-month review timeline.",
    },
    {
        "state": "Wyoming",
        "state_code": "WY",
        "license_number": "WY-SPDI-2023-001",
        "regulator": "WY Division of Banking",
        "status": "active",
        "issue_date": _now - timedelta(days=400),
        "expiry_date": _now + timedelta(days=600),
        "renewal_due_date": _now + timedelta(days=510),
        "notes": "SPDI charter. Crypto-native. No issues.",
    },
]

# ── Remedial Actions Sample Data ──────────────────────────────────────────────

SAMPLE_REMEDIAL_ACTIONS = [
    {
        "title": "Enhance SAR Filing Timeliness Controls",
        "description": "NYDFS exam identified delays in SAR filings exceeding the 30-day requirement for 12% of cases in Q3 2024. Root cause: manual triage process.",
        "source": "exam",
        "priority": "high",
        "status": "in_progress",
        "owner": "AML Team",
        "regulator": "NYDFS",
        "related_area": "AML",
        "due_date": _now + timedelta(days=45),
        "notes": "Workflow automation vendor selected. Implementation scheduled for March 2025.",
    },
    {
        "title": "Update CIP Procedures for Crypto-Native Customers",
        "description": "Self-identified gap: current CIP procedures do not address customers who are DAOs or decentralized entities. No regulatory requirement yet but proactive update needed.",
        "source": "self_identified",
        "priority": "medium",
        "status": "open",
        "owner": "Compliance Team",
        "related_area": "KYC",
        "due_date": _now + timedelta(days=90),
        "notes": "Legal review in progress.",
    },
    {
        "title": "Remediate IL License Expiration",
        "description": "Illinois MTL expired on 2025-02-08. Renewal application must be submitted and approved before resuming operations in IL.",
        "source": "self_identified",
        "priority": "critical",
        "status": "in_progress",
        "owner": "Licensing Team",
        "regulator": "IL IDFPR",
        "related_area": "MTL",
        "due_date": _now + timedelta(days=14),
        "notes": "Application drafted. Awaiting CFO signature. IL operations suspended.",
    },
    {
        "title": "Calibrate Transaction Monitoring Thresholds",
        "description": "Internal audit found alert-to-SAR conversion rate at 1.8%, below industry benchmark of 3-5%. Thresholds likely too broad.",
        "source": "audit",
        "priority": "high",
        "status": "in_progress",
        "owner": "Risk Team",
        "related_area": "AML",
        "due_date": _now + timedelta(days=60),
        "notes": "Model validation vendor engaged. Preliminary results expected April 2025.",
    },
    {
        "title": "Implement OFAC Screening for Wallet Addresses",
        "description": "Current OFAC screening covers names/entities but not on-chain wallet addresses. FinCEN guidance recommends blockchain address screening.",
        "source": "self_identified",
        "priority": "high",
        "status": "open",
        "owner": "Compliance Team",
        "related_area": "OFAC",
        "due_date": _now + timedelta(days=120),
        "notes": "Vendor RFP issued. Three vendors shortlisted.",
    },
    {
        "title": "Annual BSA/AML Training Completion",
        "description": "Annual mandatory BSA/AML training due for all staff. Current completion rate: 62%. Target: 100% by quarter end.",
        "source": "self_identified",
        "priority": "medium",
        "status": "in_progress",
        "owner": "HR / Compliance",
        "related_area": "Training",
        "due_date": _now + timedelta(days=21),
        "notes": "Reminders sent to all outstanding staff. Escalation to managers scheduled.",
    },
    {
        "title": "Resolve FinCEN Inquiry — High-Value Transfers",
        "description": "FinCEN requested documentation on 14 high-value BTC transfers flagged in Q4 2024. Response deadline March 28, 2025.",
        "source": "regulatory_inquiry",
        "priority": "critical",
        "status": "in_progress",
        "owner": "Legal / AML Team",
        "regulator": "FinCEN",
        "related_area": "AML",
        "due_date": _now + timedelta(days=17),
        "notes": "Records compiled. Legal review in progress. Do not miss deadline.",
    },
    {
        "title": "Enhanced Due Diligence — High-Risk Country Refresh",
        "description": "EDD files for customers from FATF gray-list countries require annual refresh. 23 files overdue.",
        "source": "self_identified",
        "priority": "medium",
        "status": "overdue",
        "owner": "KYC Team",
        "related_area": "EDD",
        "due_date": _now - timedelta(days=15),
        "notes": "Overdue. Prioritizing accounts with recent activity first.",
    },
    {
        "title": "Record Retention Policy Update",
        "description": "Current policy retains records for 5 years. BSA requires 5 years; some state MTLs require 7. Policy needs update to align with most restrictive requirement.",
        "source": "audit",
        "priority": "low",
        "status": "open",
        "owner": "Legal Team",
        "related_area": "Record Retention",
        "due_date": _now + timedelta(days=180),
        "notes": "Low urgency. Include in next policy review cycle.",
    },
    {
        "title": "CTR Filing for Cash-Equivalent Transactions",
        "description": "Completed — updated procedures now capture stablecoin-to-cash conversions exceeding $10,000 for CTR purposes.",
        "source": "exam",
        "priority": "high",
        "status": "completed",
        "owner": "AML Team",
        "regulator": "FinCEN",
        "related_area": "CTR",
        "due_date": _now - timedelta(days=30),
        "completion_date": _now - timedelta(days=35),
        "notes": "Closed. Verified by internal audit January 2025.",
    },
]

# ── BSA/AML Indicator Sample Data ─────────────────────────────────────────────

SAMPLE_BSA_INDICATORS = [
    {
        "program_area": "sar_filing",
        "metric_name": "SAR Filing Timeliness",
        "metric_value": "88% filed within 30 days",
        "threshold": "≥ 95% within 30 days",
        "status": "deficient",
        "responsible_team": "AML Team",
        "last_review_date": _now - timedelta(days=30),
        "next_review_date": _now + timedelta(days=30),
        "notes": "Remedial action open. Target Q2 2025 for resolution.",
    },
    {
        "program_area": "sar_filing",
        "metric_name": "SARs Filed (Last 90 Days)",
        "metric_value": "47 SARs",
        "threshold": "N/A — volume metric",
        "status": "current",
        "responsible_team": "AML Team",
        "last_review_date": _now - timedelta(days=7),
        "next_review_date": _now + timedelta(days=83),
    },
    {
        "program_area": "ctr_filing",
        "metric_name": "CTR Filing Timeliness",
        "metric_value": "100% filed within 15 days",
        "threshold": "100% within 15 days",
        "status": "current",
        "responsible_team": "AML Team",
        "last_review_date": _now - timedelta(days=14),
        "next_review_date": _now + timedelta(days=76),
    },
    {
        "program_area": "ofac_screening",
        "metric_name": "OFAC Name Screening Coverage",
        "metric_value": "100% of customers screened",
        "threshold": "100%",
        "status": "current",
        "responsible_team": "Compliance Team",
        "last_review_date": _now - timedelta(days=30),
        "next_review_date": _now + timedelta(days=60),
    },
    {
        "program_area": "ofac_screening",
        "metric_name": "OFAC Wallet Address Screening",
        "metric_value": "0% — not implemented",
        "threshold": "100% of on-chain transactions",
        "status": "deficient",
        "responsible_team": "Compliance Team",
        "last_review_date": _now - timedelta(days=30),
        "next_review_date": _now + timedelta(days=30),
        "notes": "Remedial action open. Vendor selection in progress.",
    },
    {
        "program_area": "kyc_cip",
        "metric_name": "KYC Completion Rate (New Customers)",
        "metric_value": "97.4%",
        "threshold": "≥ 99%",
        "status": "at_risk",
        "responsible_team": "KYC Team",
        "last_review_date": _now - timedelta(days=14),
        "next_review_date": _now + timedelta(days=16),
        "notes": "Decline driven by higher volume in Q1. Auto-verification backlog under review.",
    },
    {
        "program_area": "transaction_monitoring",
        "metric_name": "Alert-to-SAR Conversion Rate",
        "metric_value": "1.8%",
        "threshold": "3–5% (industry benchmark)",
        "status": "at_risk",
        "responsible_team": "Risk Team",
        "last_review_date": _now - timedelta(days=21),
        "next_review_date": _now + timedelta(days=39),
        "notes": "Model recalibration in progress. See remedial action.",
    },
    {
        "program_area": "transaction_monitoring",
        "metric_name": "Alert Review SLA (5 Business Days)",
        "metric_value": "91% reviewed within SLA",
        "threshold": "≥ 95%",
        "status": "at_risk",
        "responsible_team": "Risk Team",
        "last_review_date": _now - timedelta(days=7),
        "next_review_date": _now + timedelta(days=23),
    },
    {
        "program_area": "customer_due_diligence",
        "metric_name": "CDD Annual Refresh — Standard Risk",
        "metric_value": "98.1% current",
        "threshold": "≥ 95%",
        "status": "current",
        "responsible_team": "KYC Team",
        "last_review_date": _now - timedelta(days=30),
        "next_review_date": _now + timedelta(days=60),
    },
    {
        "program_area": "enhanced_due_diligence",
        "metric_name": "EDD Annual Refresh — High Risk",
        "metric_value": "74% current (23 overdue)",
        "threshold": "≥ 95%",
        "status": "deficient",
        "responsible_team": "KYC Team",
        "last_review_date": _now - timedelta(days=15),
        "next_review_date": _now + timedelta(days=15),
        "notes": "Overdue. Remedial action open.",
    },
    {
        "program_area": "record_retention",
        "metric_name": "BSA Record Retention Compliance",
        "metric_value": "5-year retention in place",
        "threshold": "5 years (BSA); 7 years (some states)",
        "status": "at_risk",
        "responsible_team": "Legal Team",
        "last_review_date": _now - timedelta(days=60),
        "next_review_date": _now + timedelta(days=120),
        "notes": "Policy update needed for state MTL alignment. Low urgency action open.",
    },
    {
        "program_area": "training",
        "metric_name": "BSA/AML Annual Training Completion",
        "metric_value": "62% complete",
        "threshold": "100% by Q1 end",
        "status": "at_risk",
        "responsible_team": "HR / Compliance",
        "last_review_date": _now - timedelta(days=7),
        "next_review_date": _now + timedelta(days=21),
        "notes": "Deadline: March 31, 2025. Escalation to managers underway.",
    },
    {
        "program_area": "independent_testing",
        "metric_name": "Independent BSA/AML Audit",
        "metric_value": "Last audit: Oct 2024",
        "threshold": "Annual",
        "status": "current",
        "responsible_team": "Internal Audit",
        "last_review_date": _now - timedelta(days=150),
        "next_review_date": _now + timedelta(days=215),
        "notes": "Next audit scheduled October 2025.",
    },
]
